### ISSUE TITLE
Offline mode still pulls content from web

### ISSUE THREAD

**Issue by abrownfi** [voxpupuli/puppetboard#304] opened 2016-09-20 19:40 UTC
Semantic UI still relies on web-resources, regardless of whether offline mode is set.

The pull is initiated in semantic.min.css:  @import url(https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin);

That URL results in CSS that further pulls down the individual woff files.

**Comment by corey-hammerton** [comment] 2016-09-20 20:56
Semantic UI is a third-party framework that we simply use. We can make changes to our code for CSS Importing of font files but the contents of the Semantic UI files are maintained by a third-party organization. As a result we will not be making any modifications to any of these files.

Closing this issue with a wont-fix label.

**Comment by bastelfreak** [comment] 2016-11-17 22:54
Hi,
in my opinion the parameter offline_mode is a bit misleading. As a user I would expect that it completely works while having no internet connection, not only partly. @james-powies suggested on IRC that he can provide a patch. Should we give it a try?

**Comment by james-powis** [comment] 2016-11-17 22:59
Being offline is all find and well, and being behind a firewall with outbound reject policies works well too. 

However a firewall policy where the action is to drop requires http to timeout before each page of puppetboard will properly load. This leads to the argument "change your firewall policy to reject", doing so actually causes more problems because `netstat -an | grep SYN_SENT` helps identify issues such as this, and will not work with reject.

**Comment by james-powis** [comment] 2016-11-18 00:34
basic monkey patch is done, just pending getting successful tests written to prevent regression:
https://github.com/voxpupuli/puppetboard/pull/316

**Comment by juniorsysadmin** [comment] 2016-12-20 09:18
Changed label to bug since 'offline' is not as one would expect. Patching third-party frameworks is definitely a nono though.

**Comment by mterzo** [comment] 2016-12-23 05:04
@juniorsysadmin Yeah, patching 3rd party sucks.  Here's the suggestion: 
https://github.com/Semantic-Org/Semantic-UI/issues/1521

**Closed** 2017-07-08 14:51 UTC
Labels: bug
