### ISSUE TITLE
Problem with installing puppetboard. It was fine about a week ago :-(

### ISSUE THREAD

**Issue by jimezdoesit** [voxpupuli/puppetboard#343] opened 2017-01-30 23:17 UTC
I had to reinstall puppetdb & puppetboard. I have all of my stuff in gitlab. When I tried to reinstall puppetboard I got the below error. The only fix is to copy over /srv/puppetboard from another machine :-( 

Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns: ValueError: I/O operation on closed file

Error: true  && virtualenv --system-site-packages -p python /srv/puppetboard/virtenv-puppetboard && /srv/puppetboard/virtenv-puppetboard/bin/pip wheel --help > /dev/null 2>&1 && { /srv/puppetboard/virtenv-puppetboard/bin/pip wheel --version > /dev/null 2>&1 || wheel_support_flag='--no-use-wheel'; } ; { /srv/puppetboard/virtenv-puppetboard/bin/pip --log /srv/puppetboard/virtenv-puppetboard/pip.log install   $wheel_support_flag --upgrade pip setuptools || /srv/puppetboard/virtenv-puppetboard/bin/pip --log /srv/puppetboard/virtenv-puppetboard/pip.log install    --upgrade pip setuptools ;} returned 1 instead of one of [0]
Error: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns: change from notrun to 0 failed: true  && virtualenv --system-site-packages -p python /srv/puppetboard/virtenv-puppetboard && /srv/puppetboard/virtenv-puppetboard/bin/pip wheel --help > /dev/null 2>&1 && { /srv/puppetboard/virtenv-puppetboard/bin/pip wheel --version > /dev/null 2>&1 || wheel_support_flag='--no-use-wheel'; } ; { /srv/puppetboard/virtenv-puppetboard/bin/pip --log /srv/puppetboard/virtenv-puppetboard/pip.log install   $wheel_support_flag --upgrade pip setuptools || /srv/puppetboard/virtenv-puppetboard/bin/pip --log /srv/puppetboard/virtenv-puppetboard/pip.log install    --upgrade pip setuptools ;} returned 1 instead of one of [0]

**Comment by mterzo** [comment] 2017-01-30 23:30
Can you provide the pip log.

**Comment by jimezdoesit** [comment] 2017-01-31 02:18
I have attached the pip.log for your review.

[pip.txt](https://github.com/voxpupuli/puppetboard/files/740965/pip.txt)

**Comment by mterzo** [comment] 2017-01-31 06:54
This is a duplicate of https://github.com/voxpupuli/puppet-puppetboard/issues/163 which is a problem  with what looks to be something in setup tools getting auto upgraded in the virtual environment.

**Closed by mterzo** 2017-01-31 06:54 UTC
Labels: duplicate
