### ISSUE TITLE
Metrics URL wrong on puppetdb 6.10.0

### ISSUE THREAD

**Issue by ltning** [voxpupuli/puppetboard#573] opened 2020-05-24 19:12 UTC
I'm getting the following on FreeBSD 12.1, puppetdb 6.10.0:
```
INFO:puppetboard.utils:PuppetDB Version 6.10.0
ERROR:pypuppetdb.api: localhost:8080 over HTTP.
ERROR:puppetboard.utils:404 Client Error: Not Found for url: http://localhost:8080/metrics/v1/mbeans
```

Looked at the sources briefly, not sure why it'd pick v1 endpoint here..

**Comment by sebastianrakel** [comment] 2020-10-01 10:09
Hey, it took some time for an answer, but i can't reproduce it. 
Do you have still this error on the newest version?

**Comment by gdubicki** [comment] 2022-01-15 17:27
Closing as it looks outdated. Please reopen if needed.

**Closed by gdubicki** 2022-01-15 17:27 UTC
